#!/bin/sh
# Gets the files that aren't spriteSizexspriteSize and dumps the name, current size and original size to wrongsizeSprite.txt
spriteSize=64
pathname="$HOME/Desktop/TestConvert/*"
var=$(identify "$pathname" | grep -v "$spriteSize"x"$spriteSize" | awk '{printf "%s\t%s\t%s\n", $1, $3, $4}')
#var=$(identify resource/frames/* | grep -v 16x16 | awk '{printf ("%5s\t%s\t%s\n", $1, $3, $4)}' | cut -c 17-)

echo "$var" | wc -l

echo "$var" | while read -r line ; 
do
	# awk -F[x] splits char into left and right of whatever x is
	varx=$(echo "$line" | awk '{print $2}' | awk -F\[x\] '{print $1}')
	vary=$(echo "$line" | awk '{print $2}' | awk -F\[x\] '{print $2}')
	

	if [ "$varx" -ne "$spriteSize" ]
	then
		diffx=$((varx - spriteSize))
		if [ "$diffx" -lt 0 ]
		then
			convert "$(echo "$line" | awk '{print $1}')" -resize "$spriteSize" "$(echo "$line" | awk '{printf "Sized%s", $1}')"
		else
			convert "$(echo "$line" | awk '{print $1}')" -crop "$spriteSize"x"$spriteSize"+"$diffx"+0 ~/Desktop/TestConvert/result2.png
		fi
	fi
	
	if [ "$vary" -ne $spriteSize ]
	then 
		diffy=$((vary - spriteSize))
		if [ "$diffy" -lt 0 ]
		then
			convert "$(echo "$line" | awk '{print $1}')" -resize x"$spriteSize" ~/Desktop/TestConvert/result3.png
		else
			convert "$(echo "$line" | awk '{print $1}')" -crop "$spriteSize"x"$spriteSize"+0+"$diffy" ~/Desktop/TestConvert/result4.png
		fi
	fi
done

