#!/bin/sh

# Gets the files that aren't 16x16 and dumps the name, current size and original size to wrongsizeSprite.txt
var=$(identify resource/frames/* | grep -v 16x16 | awk '{printf ("%5s\t%s\t%s\n", $1, $3, $4)}' | cut -c 17-)
var=$(identify resource/frames/* | grep -v 16x16 | awk '{print $1, $3, $4}' | cut -c 17-)
echo $var > wrongsizeSprite.txt


# Might need escape character before [ and ]
echo $var | while read -r line ; 
do
	# awk -F[x] splits char into left and right of whatever x is
	varx=$(echo "$line" | cut -f 2 | awk -F\[x\] '{print $1}')
	vary=$(echo "$line" | cut -f 2 | awk -F\[x\] '{print $2}')
	echo "$varx"
	echo "$vary";
done

